ENH: Add capabilities for changing UI
Kitware/itk-vtk-viewer pull request #528
Opened 2022-07-21 17:39 UTC by labdala

This adds the capability of the user choose the ui (e.g., 'view(image, ui='pydata-sphinx') in itkwidgets. Specifically, it includes ui argument to setImage and setPointSets.

2022-07-21 18:14 UTC, thewtex requested changes
Instead, make these changes here:

https://github.com/Kitware/itk-vtk-viewer/blob/407515bbd5b57de20b33bce65fec927de886d141/src/createViewer.js#L189-L204

Conditioning on if `uiMachineOptions` === `pydata-sphinx` also `mui`.

So, we will support.

1) `"reference"` -- current
2) `"mui"`: point to jsDelivr
3) `"pydata-sphinx"` - point jsDeliver
4) `{ href: 'my-custom url', export: 'default' }`.

2022-07-26 19:20 UTC, thewtex requested changes

2022-07-26 19:20 UTC, thewtex commented on src/imJoyPluginAPI.js
> +  async setPointSets(pointSets, config) {
remove `, config`

2022-07-28 18:12 UTC, labdala commented
It has been refactored in #535

2022-07-28 18:12 UTC, closed without merging