ENH: Choose UI refactor
Kitware/itk-vtk-viewer pull request #535
Opened 2022-07-28 17:05 UTC by labdala

@thewtex @PaulHax

2022-07-28 18:11 UTC, labdala commented
Adds changes requested by @thewtex in #528

2022-08-11 14:31 UTC, thewtex requested changes

2022-08-11 14:31 UTC, thewtex commented on src/createViewer.js
> +          'https://www.jsdelivr.com/package/npm/itk-viewer-material-ui@0/dist/materialUIMachineOptions.js.es.js',
`www` -> `cdn`, etc.

2022-08-11 14:31 UTC, thewtex commented on src/createViewer.js
> +          'https://cdn.jsdelivr.net/npm/itk-viewer-bootstrap-ui@0/dist/itk-viewer-bootstrap-ui.es.js',
`itk-viewer-bootstrap-ui` -> new name

2022-08-11 18:39 UTC, thewtex approved these changes

2022-08-11 18:40 UTC, thewtex commented
:sparkler:

2022-08-11 18:40 UTC, merged