feat(scaleSelector): spinner shows when loading image
Kitware/itk-vtk-viewer pull request #604
Opened 2022-10-10 23:43 UTC by PaulHax

2022-10-13 01:47 UTC, thewtex commented
@PaulHax getting there!

Naming nitpick: can the events be `IMAGE_UPDATE_STARTED` and `IMAGE_UPDATE_FINISHED` to be more explicit and avoid passive voice?

Testing locally with [this file](https://data.kitware.com/#item/63476e0911dab81428208e27) I only see a flash of the progress icon during updates. Perhaps the events need to be scoped even further out?

2022-10-13 14:22 UTC, thewtex commented
Re the IDR use case discussed: https://github.com/InsightSoftwareConsortium/itkwidgets/issues/548 We could also turn the picture icon next to the Image selector into a spinner as the image is loading.

2022-10-13 19:31 UTC, PaulHax commented
Tink we got it by waiting to turn off spinner after first render.  `renderWindow.render()` is ignored by vtk.js if interactor is animating so the slow load texture on GPU part was happening later when rotate=true.

Do we want the spinner next to the picture icon?

2022-10-14 14:46 UTC, thewtex commented
@PaulHax very nice!!

> Do we want the spinner next to the picture icon?

That would be excellent

2022-10-14 22:02 UTC, PaulHax commented
Spinner moved.

2022-10-17 13:16 UTC, thewtex requested changes
Working wonderfully locally.

A few more tweaks noted inline to pave the way for other datasets.

2022-10-17 13:16 UTC, thewtex commented on src/UI/reference-ui/src/Layers/layersUIMachineOptions.js
> +      idle,
To enable the same behavior for point sets, geometry, can the `imageUpdating` and `idle` be updated to `startDataUpdate`, `finishDataUpdate`? Internally switch on the actor `type` like `toggleLayerVisibility`.

2022-10-18 00:32 UTC, thewtex approved these changes
:100:

2022-10-18 00:32 UTC, merged